import React from "react";
import { ArrowLeft, ArrowRight, Boxes, LockKeyhole, ShieldCheck, Users, Workflow } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import "./home.css";

const CONTENT = {
  platform: { eyebrow: "EPS platform", title: "One governed source-to-pay platform", intro: "Enterprise Procurement System connects request, approval, sourcing, ordering, receiving and payment without exposing protected operational data.", icon: Workflow, sections: [["Connected workflow", "Purchase requests, approval tasks, RFQs, quotations, purchase orders, receipts, invoices and payments use their respective backend workflows."], ["Role-based workspaces", "Each signed-in user is routed to the capabilities authorized for their backend role."], ["Operational visibility", "Current records are loaded from the backend with clear loading, empty and error states."]] },
  solutions: { eyebrow: "EPS solutions", title: "Built for every procurement stakeholder", intro: "EPS gives each team a focused workspace while maintaining a controlled, auditable procurement lifecycle.", icon: Users, sections: [["Procurement and finance", "Manage sourcing, comparisons, purchase orders, invoice verification and payment processing through authorized workflows."], ["Warehouse and operations", "Receive goods, record GRNs and work with live inventory records where the backend provides support."], ["People and governance", "HR, managers, administrators and auditors use organization data only through the roles and APIs they are authorized to access."]] },
  governance: { eyebrow: "EPS governance", title: "Security and auditability by design", intro: "Access is enforced by the backend. The public site explains the platform but never exposes organizational records.", icon: ShieldCheck, sections: [["Role-based access", "Authenticated APIs enforce permissions for business data and workflow actions."], ["Audit controls", "Supported transactions retain backend history and audit-log records for authorized review."], ["Data protection", "Vendor and other scoped views remain unavailable until their backend isolation can be verified."]] },
};

export default function PublicInfo() {
  const { page } = useParams();
  const content = CONTENT[page] || CONTENT.platform;
  const Icon = content.icon;
  return <main className="eps-home"><section className="eps-hero" style={{ minHeight: "calc(100vh - 76px)", display: "grid", placeItems: "center" }}><div className="eps-container" style={{ maxWidth: 1060 }}><Link to="/" className="eps-btn eps-btn-ghost" style={{ display: "inline-flex", textDecoration: "none", marginBottom: 34 }}><ArrowLeft size={16} /> Back to home</Link><div className="eps-hero-grid"><div className="eps-hero-copy"><span className="eps-eyebrow"><Icon size={14} /> {content.eyebrow}</span><h1 className="eps-hero-title">{content.title}</h1><p className="eps-hero-sub">{content.intro}</p><Link className="eps-btn eps-btn-primary" to="/login" style={{ display: "inline-flex", textDecoration: "none" }}>Sign in to EPS <ArrowRight size={17} /></Link></div><div className="eps-hero-visual"><div className="eps-visual-card"><div className="eps-visual-head"><div className="eps-visual-logo"><LockKeyhole size={20} /></div><div><strong>Enterprise Procurement System</strong><span>Public platform information</span></div></div>{content.sections.map(([heading, copy]) => <div className="eps-audit-row" key={heading}><div className="eps-feature-icon"><Boxes size={18} /></div><div className="eps-audit-body"><strong>{heading}</strong><span>{copy}</span></div></div>)}</div></div></div></div></section></main>;
}
