import React, { useCallback, useEffect, useState } from "react";
import { Boxes, Database, RefreshCw, Users, XCircle } from "lucide-react";
import { getEmployees } from "../../../../../services/employeeService";
import { getInventory } from "../../../../../services/inventoryService";
import { getPurchaseRequests } from "../../../../../services/purchaseRequestService";
import { asList } from "../../../../../services/serviceUtils";
import { getVendors } from "../../../../../services/vendorService";

const Card = ({ title, icon: Icon, rows, render }) => <section style={{ background: "#fff", border: "1px solid #e7ebf0", borderRadius: 12, padding: 18 }}><h2 style={{ margin: "0 0 12px", fontSize: 16, display: "flex", gap: 8, alignItems: "center" }}><Icon size={17} color="#2563eb" /> {title} ({rows.length})</h2><div style={{ maxHeight: 230, overflow: "auto" }}>{rows.length ? rows.map(render) : <p style={{ color: "#68778a" }}>No records found.</p>}</div></section>;
export default function OrgMasterDataView() {
  const [data, setData] = useState({ employees: [], vendors: [], requests: [], inventory: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [employees, vendors, requests, inventory] = await Promise.all([getEmployees({ size: 50 }), getVendors({ size: 50 }), getPurchaseRequests({ size: 50 }), getInventory({ size: 50 })]); setData({ employees: asList(employees), vendors: asList(vendors), requests: asList(requests), inventory: asList(inventory) }); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  return <div style={{ padding: 24 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", marginBottom: 24 }}><div><h1 style={{ margin: 0, display: "flex", gap: 10, alignItems: "center" }}><Database color="#2563eb" /> Organization Data View</h1><p style={{ color: "#68778a" }}>Live master and operational records permitted for this role.</p></div><button onClick={load} style={{ border: "1px solid #d9dee6", borderRadius: 8, background: "#fff", padding: "9px 14px", cursor: "pointer" }}><RefreshCw size={14} /> Refresh</button></div>{error && <div style={{ color: "#b91c1c", marginBottom: 16 }}><XCircle size={16} /> {error} <button onClick={load}>Retry</button></div>}{loading ? <p>Loading organization data…</p> : <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))", gap: 16 }}><Card title="Employees" icon={Users} rows={data.employees} render={(item) => <p key={item.id} style={{ borderBottom: "1px solid #f0f2f5", paddingBottom: 8 }}><strong>{item.fullName || `${item.firstName || ""} ${item.lastName || ""}`}</strong><br /><small>{item.departmentName || "Unassigned"} · {item.active ? "Active" : "Inactive"}</small></p>} /><Card title="Vendors" icon={Database} rows={data.vendors} render={(item) => <p key={item.id} style={{ borderBottom: "1px solid #f0f2f5", paddingBottom: 8 }}><strong>{item.vendorName || item.name}</strong><br /><small>{item.status || "—"}</small></p>} /><Card title="Purchase requests" icon={Database} rows={data.requests} render={(item) => <p key={item.id} style={{ borderBottom: "1px solid #f0f2f5", paddingBottom: 8 }}><strong>{item.requestNumber || item.id}</strong><br /><small>{item.status}</small></p>} /><Card title="Inventory" icon={Boxes} rows={data.inventory} render={(item) => <p key={item.id} style={{ borderBottom: "1px solid #f0f2f5", paddingBottom: 8 }}><strong>{item.productName}</strong><br /><small>{item.warehouseName} · Available: {item.availableQuantity}</small></p>} /></div>}</div>;
}
