package com.procurement.event;

/** Stable workflow event names for auditing and downstream notifications. */
public enum BusinessEventType {
    PURCHASE_REQUEST_CREATED, PURCHASE_REQUEST_SUBMITTED, PURCHASE_REQUEST_APPROVED, PURCHASE_REQUEST_REJECTED, PURCHASE_REQUEST_CANCELLED, PURCHASE_REQUEST_UPDATED, PURCHASE_REQUEST_COMPLETED,
    RFQ_CREATED, RFQ_PUBLISHED,
    QUOTATION_SUBMITTED, QUOTATION_APPROVED, QUOTATION_REJECTED,
    QUOTATION_COMPARISON_COMPLETED,
    PURCHASE_ORDER_GENERATED, PURCHASE_ORDER_APPROVED,
    GOODS_RECEIVED, INVENTORY_UPDATED,
    INVOICE_CREATED, INVOICE_APPROVED,
    THREE_WAY_MATCH_COMPLETED,
    PAYMENT_PROCESSED, PAYMENT_COMPLETED,
    NOTIFICATION_SENT, REPORT_EXPORTED, DASHBOARD_VIEWED,
    LOGIN, LOGOUT
}
