import React, { useCallback, useEffect, useState } from "react";
import { CheckCircle2, FileCheck2, RefreshCw, Search, XCircle } from "lucide-react";
import { approveInvoice, getInvoices, matchInvoice } from "../../../../../services/invoiceService";
import { asList } from "../../../../../services/serviceUtils";
import { getThreeWayMatches } from "../../../../../services/threeWayMatchService";

const money = (value, currency = "") => `${currency ? `${currency} ` : ""}${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

const FinanceInvoiceMgmt = () => {
  const [invoices, setInvoices] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [matches, setMatches] = useState([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [busyId, setBusyId] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [invoiceData, matchData] = await Promise.all([getInvoices({ keyword: search || undefined, status: status || undefined, size: 100 }), getThreeWayMatches({ size: 100 })]); setInvoices(asList(invoiceData)); setMatches(asList(matchData)); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [search, status]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  const act = async (invoice, action) => { setBusyId(invoice.id); setError(""); try { const updated = action === "match" ? await matchInvoice(invoice.id) : await approveInvoice(invoice.id); setInvoices((items) => items.map((item) => item.id === updated.id ? updated : item)); } catch (e) { setError(e.message); } finally { setBusyId(null); } };
  return <div className="fin-invoice-mgmt-container" style={{ padding: 20 }}>
    <div className="fin-page-header" style={{ marginBottom: 24 }}><h1 className="fin-page-title" style={{ display: "flex", alignItems: "center", gap: 10 }}><FileCheck2 color="#f8b400" /> Accounts Payable Invoice Verification Center</h1><p className="fin-page-subtitle">Live vendor invoices and backend-driven verification status.</p></div>
    <div className="fin-card" style={{ padding: 16, marginBottom: 20, display: "flex", gap: 12, flexWrap: "wrap" }}><label><Search size={15} style={{ marginRight: 6 }} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search invoices" className="fin-form-input" /></label><select value={status} onChange={(e) => setStatus(e.target.value)} className="fin-form-select"><option value="">All statuses</option>{["RECEIVED", "UNDER_VERIFICATION", "MATCH_PENDING", "MATCHED", "APPROVED", "REJECTED", "PAID"].map((value) => <option key={value}>{value}</option>)}</select><button onClick={load} className="fin-sidebar-toggle"><RefreshCw size={15} /> Refresh</button></div>
    {error && <div className="fin-card" style={{ padding: 16, color: "#b91c1c", marginBottom: 16 }}><XCircle size={16} /> {error} <button onClick={load}>Retry</button></div>}
    <div className="fin-card" style={{ overflow: "hidden", marginBottom: 20 }}><div className="fin-table-container"><table className="fin-table"><thead><tr><th>Invoice</th><th>PO / GRN</th><th>Vendor</th><th>Invoice date</th><th>Due date</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan="8" style={{ padding: 32, textAlign: "center" }}>Loading invoices…</td></tr> : invoices.length === 0 ? <tr><td colSpan="8" style={{ padding: 32, textAlign: "center" }}>No invoices found.</td></tr> : invoices.map((invoice) => <tr key={invoice.id}><td><strong>{invoice.invoiceNumber}</strong><br /><small>{invoice.vendorInvoiceNumber}</small></td><td>{invoice.purchaseOrderId || "—"} / {invoice.goodsReceiptNoteId || "—"}</td><td>{invoice.vendorName || "—"}</td><td>{invoice.invoiceDate || "—"}</td><td>{invoice.dueDate || "—"}</td><td>{money(invoice.grandTotal, invoice.currency)}</td><td>{invoice.status}</td><td style={{ whiteSpace: "nowrap" }}>{invoice.status === "MATCH_PENDING" || invoice.status === "UNDER_VERIFICATION" || invoice.status === "RECEIVED" ? <button disabled={busyId === invoice.id} onClick={() => act(invoice, "match")} className="fin-btn-approve">Match</button> : null}{invoice.status === "MATCHED" ? <button disabled={busyId === invoice.id} onClick={() => act(invoice, "approve")} className="fin-btn-approve"><CheckCircle2 size={14} /> Approve</button> : null}</td></tr>)}</tbody></table></div></div>
    <div className="fin-card" style={{ overflow: "hidden" }}><div style={{ padding: "14px 18px", fontWeight: 700 }}>Three-way match results (PO + GRN + invoice)</div><div className="fin-table-container"><table className="fin-table"><thead><tr><th>Match</th><th>PO</th><th>GRN</th><th>Invoice</th><th>Vendor</th><th>Status</th><th>Result</th></tr></thead><tbody>{loading ? <tr><td colSpan="7" style={{ padding: 20, textAlign: "center" }}>Loading match state…</td></tr> : matches.length === 0 ? <tr><td colSpan="7" style={{ padding: 20, textAlign: "center" }}>No three-way matches found.</td></tr> : matches.map((match) => <tr key={match.id}><td>{match.matchNumber}</td><td>{match.purchaseOrderNumber || match.purchaseOrderId}</td><td>{match.goodsReceiptNoteNumber || match.goodsReceiptNoteId}</td><td>{match.invoiceNumber || match.invoiceId}</td><td>{match.vendorName || "—"}</td><td>{match.status}</td><td>{match.overallResult || "Not generated"}</td></tr>)}</tbody></table></div></div>
  </div>;
};
export default FinanceInvoiceMgmt;
