import React, { useCallback, useEffect, useState } from "react";
import { CheckCircle2, CreditCard, RefreshCw, XCircle } from "lucide-react";
import { approvePayment, getPayments, processPayment } from "../../../../../services/paymentService";
import { asList } from "../../../../../services/serviceUtils";

const amount = (payment) => `${payment.currency || ""} ${Number(payment.netAmount ?? payment.grossAmount ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`;
const PaymentApprovals = () => {
  const [payments, setPayments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setPayments(asList(await getPayments({ status: status || undefined, size: 100 }))); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [status]);
  useEffect(() => { load(); }, [load]);
  const transition = async (payment, action) => { setBusy(payment.id); setError(""); try { const changed = action === "approve" ? await approvePayment(payment.id) : await processPayment(payment.id); setPayments((items) => items.map((item) => item.id === changed.id ? changed : item)); } catch (e) { setError(e.message); } finally { setBusy(null); } };
  return <div style={{ padding: 20 }}><div className="fin-page-header" style={{ marginBottom: 24 }}><h1 className="fin-page-title" style={{ display: "flex", alignItems: "center", gap: 10 }}><CreditCard color="#f8b400" /> Payment Approvals</h1><p className="fin-page-subtitle">Authorize payments only from the backend payment queue.</p></div>
    <div className="fin-card" style={{ padding: 16, display: "flex", gap: 12, marginBottom: 20 }}><select className="fin-form-select" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{["DRAFT", "SCHEDULED", "APPROVED", "PROCESSING", "PAID", "FAILED", "CANCELLED"].map((item) => <option key={item}>{item}</option>)}</select><button className="fin-sidebar-toggle" onClick={load}><RefreshCw size={15} /> Refresh</button></div>
    {error && <div className="fin-card" style={{ padding: 16, color: "#b91c1c", marginBottom: 16 }}><XCircle size={16} /> {error} <button onClick={load}>Retry</button></div>}
    <div className="fin-card"><div className="fin-table-container"><table className="fin-table"><thead><tr><th>Payment</th><th>Invoice</th><th>PO</th><th>Vendor</th><th>Scheduled</th><th>Method</th><th>Net amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading ? <tr><td colSpan="9" style={{ padding: 32, textAlign: "center" }}>Loading payments…</td></tr> : payments.length === 0 ? <tr><td colSpan="9" style={{ padding: 32, textAlign: "center" }}>No payments found.</td></tr> : payments.map((payment) => <tr key={payment.id}><td>{payment.paymentNumber}</td><td>{payment.invoiceNumber || payment.invoiceId}</td><td>{payment.purchaseOrderNumber || payment.purchaseOrderId}</td><td>{payment.vendorName || "—"}</td><td>{payment.scheduledDate || payment.paymentDate || "—"}</td><td>{payment.paymentMethod}</td><td>{amount(payment)}</td><td>{payment.status}</td><td>{payment.status === "SCHEDULED" ? <button disabled={busy === payment.id} className="fin-btn-approve" onClick={() => transition(payment, "approve")}><CheckCircle2 size={14} /> Approve</button> : payment.status === "APPROVED" ? <button disabled={busy === payment.id} className="fin-btn-approve" onClick={() => transition(payment, "process")}>Process</button> : "—"}</td></tr>)}</tbody></table></div></div></div>;
};
export default PaymentApprovals;
