import React, { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Clock, RefreshCw, XCircle } from "lucide-react";
import { completePayment, getPayments } from "../../../../../services/paymentService";
import { asList } from "../../../../../services/serviceUtils";
const ProcurementPaymentTracking = () => {
  const [payments, setPayments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setPayments(asList(await getPayments({ size: 100 }))); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const complete = async (payment) => { setBusy(payment.id); setError(""); try { const changed = await completePayment(payment.id); setPayments((items) => items.map((item) => item.id === changed.id ? changed : item)); } catch (e) { setError(e.message); } finally { setBusy(null); } };
  return <div className="fin-tracking-container" style={{ padding: 20 }}><div className="fin-page-header" style={{ marginBottom: 24 }}><h1 className="fin-page-title" style={{ display: "flex", alignItems: "center", gap: 10 }}><Clock color="#f8b400" /> Procurement Payment Tracking</h1><p className="fin-page-subtitle">Live payment lifecycle status and settlement details.</p></div><div className="fin-card" style={{ padding: 16, marginBottom: 20 }}><button className="fin-sidebar-toggle" onClick={load}><RefreshCw size={15} /> Refresh</button></div>{error && <div className="fin-card" style={{ padding: 16, color: "#b91c1c", marginBottom: 16 }}><XCircle size={16} /> {error} <button onClick={load}>Retry</button></div>}<div className="fin-card"><div className="fin-table-container"><table className="fin-table"><thead><tr><th>Payment</th><th>Vendor</th><th>Invoice / Match</th><th>Payment date</th><th>Reference</th><th>Net amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading ? <tr><td colSpan="8" style={{ padding: 32, textAlign: "center" }}>Loading payment tracking…</td></tr> : payments.length === 0 ? <tr><td colSpan="8" style={{ padding: 32, textAlign: "center" }}>No payments found.</td></tr> : payments.map((payment) => <tr key={payment.id}><td>{payment.paymentNumber}</td><td>{payment.vendorName || "—"}</td><td>{payment.invoiceNumber || payment.invoiceId} / {payment.threeWayMatchNumber || payment.threeWayMatchId}</td><td>{payment.paymentDate || "—"}</td><td>{payment.paymentReference || "—"}</td><td>{payment.currency || ""} {Number(payment.netAmount ?? payment.grossAmount ?? 0).toLocaleString()}</td><td>{payment.status}</td><td>{payment.status === "PROCESSING" ? <button className="fin-btn-approve" disabled={busy === payment.id} onClick={() => complete(payment)}><CheckCircle2 size={14} /> Complete</button> : "—"}</td></tr>)}</tbody></table></div></div></div>;
};
export default ProcurementPaymentTracking;
