import React, { useState, useEffect, useCallback } from "react";
import { Bell, CheckCircle2, RefreshCw, Loader2, AlertCircle, Archive, MailOpen, Mail } from "lucide-react";
import { apiGet, apiPost } from "../../../../../services/apiClient";
import { formatDateIN } from "../../../../../utils/format";

const SuperNotificationsCenter = () => {
  const [notifs, setNotifs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [statusFilter, setStatusFilter] = useState(""); // "" | SENT | READ | ARCHIVED
  const [toast, setToast] = useState(null);

  const triggerToast = (msg) => {
    setToast(msg);
    setTimeout(() => setToast(null), 3500);
  };

  const loadData = useCallback(async () => {
    setLoading(true);
    setError("");
    const params = new URLSearchParams({ page: "0", size: "50", sort: "createdAt", direction: "desc" });
    if (statusFilter) params.set("status", statusFilter);
    try {
      const data = await apiGet(`/api/notifications?${params.toString()}`);
      setNotifs(data?.content || []);
    } catch (err) {
      setError(err.message || "Failed to load notifications.");
    } finally {
      setLoading(false);
    }
  }, [statusFilter]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const markRead = async (n) => {
    try {
      await apiPost(`/api/notifications/${n.id}/mark-read`, {});
      triggerToast(`Notification "${n.title}" marked as read.`);
      loadData();
    } catch (err) {
      triggerToast(err.message || "Could not mark notification as read.");
    }
  };

  const markAllRead = async () => {
    const unread = notifs.filter((n) => n.status !== "READ");
    for (const n of unread) {
      try {
        await apiPost(`/api/notifications/${n.id}/mark-read`, {});
      } catch {
        // continue marking the rest
      }
    }
    triggerToast(`${unread.length} notification(s) marked as read.`);
    loadData();
  };

  const archive = async (n) => {
    try {
      await apiPost(`/api/notifications/${n.id}/archive`, {});
      triggerToast("Notification archived.");
      loadData();
    } catch (err) {
      triggerToast(err.message || "Could not archive notification.");
    }
  };

  const unreadCount = notifs.filter((n) => n.status !== "READ").length;

  return (
    <div className="sadmin-notifications-container" style={{ padding: "20px" }}>
      {toast && (
        <div style={{ position: "fixed", bottom: "24px", right: "24px", background: "#111", color: "#fff", padding: "12px 24px", borderRadius: "8px", boxShadow: "0 8px 24px rgba(0,0,0,0.2)", zIndex: 1000, fontWeight: "700", fontSize: "14px", borderLeft: "4px solid #f8b400" }}>
          {toast}
        </div>
      )}

      {/* Header */}
      <div className="sadmin-page-header" style={{ marginBottom: "20px", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "12px" }}>
        <div>
          <h1 className="sadmin-page-title" style={{ display: "flex", alignItems: "center", gap: "10px", fontSize: "24px", fontWeight: "700", color: "#111" }}>
            <Bell color="#f8b400" size={28} /> Notifications Center
          </h1>
          <p className="sadmin-page-subtitle" style={{ color: "#666", fontSize: "14px", marginTop: "4px" }}>
            System events generated by backend workflows — approvals, KYC, budgets, low stock and more. {unreadCount} unread in this view.
          </p>
        </div>
        <div style={{ display: "flex", gap: "10px" }}>
          <button className="sadmin-btn-primary-sm" style={{ background: "#f8f9fb", color: "#111", border: "1px solid #d9d9d9" }} onClick={loadData} disabled={loading}>
            <RefreshCw size={15} /> Refresh
          </button>
          <button className="sadmin-btn-primary-sm" onClick={markAllRead}>
            <CheckCircle2 size={16} /> Mark All Read
          </button>
        </div>
      </div>

      {error && (
        <div style={{ display: "flex", alignItems: "center", gap: "10px", background: "rgba(220,38,38,0.08)", border: "1px solid rgba(220,38,38,0.3)", color: "#dc2626", padding: "12px 16px", borderRadius: "10px", marginBottom: "20px", fontSize: "14px", fontWeight: "600" }}>
          <AlertCircle size={18} /> {error}
        </div>
      )}

      {/* Status tabs */}
      <div style={{ display: "flex", gap: "12px", borderBottom: "1px solid #ececec", marginBottom: "20px" }}>
        {[
          { value: "", label: "All" },
          { value: "SENT", label: "Unread" },
          { value: "READ", label: "Read" },
          { value: "EXPIRED", label: "Archived" },
        ].map((t) => (
          <button
            key={t.value}
            onClick={() => setStatusFilter(t.value)}
            style={{
              background: "none",
              border: "none",
              padding: "10px 16px",
              fontSize: "15px",
              fontWeight: statusFilter === t.value ? "700" : "500",
              color: statusFilter === t.value ? "#d97706" : "#666",
              borderBottom: statusFilter === t.value ? "3px solid #f8b400" : "3px solid transparent",
              cursor: "pointer",
            }}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* List */}
      <div className="sadmin-card" style={{ background: "#fff", border: "1px solid #ececec", borderRadius: "12px", padding: "20px" }}>
        {loading ? (
          <div style={{ display: "flex", justifyContent: "center", alignItems: "center", padding: "48px", gap: "10px", color: "#666" }}>
            <Loader2 size={20} className="login-spin" /> Loading notifications...
          </div>
        ) : notifs.length === 0 ? (
          <div style={{ padding: "48px", textAlign: "center", color: "#888" }}>
            No notifications found. Notifications are created by backend workflow events.
          </div>
        ) : (
          <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
            {notifs.map((n) => {
              const isUnread = n.status !== "READ";
              return (
                <div
                  key={n.id}
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "14px",
                    padding: "16px",
                    borderRadius: "12px",
                    background: isUnread ? "rgba(248, 180, 0, 0.08)" : "#f8f9fb",
                    border: isUnread ? "1px solid #f8b400" : "1px solid #ececec",
                  }}
                >
                  <div style={{ width: "40px", height: "40px", borderRadius: "10px", background: "#ffffff", border: "1px solid #d9d9d9", display: "flex", alignItems: "center", justifyContent: "center", color: "#f8b400", flexShrink: 0 }}>
                    {isUnread ? <Mail size={20} /> : <MailOpen size={20} />}
                  </div>

                  <div style={{ flex: 1 }}>
                    <div style={{ display: "flex", justifyContent: "space-between", gap: "12px", marginBottom: "2px", flexWrap: "wrap" }}>
                      <h4 style={{ fontSize: "15px", color: "#111111", fontWeight: "700", margin: 0 }}>
                        {n.title}
                        {isUnread && <span style={{ display: "inline-block", width: "8px", height: "8px", borderRadius: "50%", background: "#f8b400", marginLeft: "8px" }} />}
                      </h4>
                      <span style={{ fontSize: "12px", color: "#666666", whiteSpace: "nowrap" }}>{formatDateIN(n.createdAt)}</span>
                    </div>
                    <p style={{ fontSize: "13px", color: "#555555", lineHeight: "1.4", margin: "4px 0 8px" }}>{n.message}</p>
                    <div style={{ display: "flex", gap: "8px", alignItems: "center", flexWrap: "wrap" }}>
                      <span style={{ fontSize: "11px", fontWeight: "700", background: "rgba(37,99,235,0.08)", color: "#2563eb", padding: "2px 8px", borderRadius: "10px" }}>{n.type || "SYSTEM"}</span>
                      {n.referenceType && <span style={{ fontSize: "11px", color: "#888" }}>{n.referenceType} #{n.referenceId}</span>}
                      {isUnread && (
                        <button style={{ marginLeft: "auto", display: "inline-flex", alignItems: "center", gap: "5px", fontSize: "12px", fontWeight: "700", color: "#059669", background: "none", border: "none", cursor: "pointer" }} onClick={() => markRead(n)}>
                          <CheckCircle2 size={14} /> Mark read
                        </button>
                      )}
                      <button style={{ display: "inline-flex", alignItems: "center", gap: "5px", fontSize: "12px", fontWeight: "700", color: "#666", background: "none", border: "none", cursor: "pointer" }} onClick={() => archive(n)}>
                        <Archive size={14} /> Archive
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

export default SuperNotificationsCenter;
