package com.procurement.report.controller;

import com.procurement.common.response.*;
import com.procurement.report.dto.request.ReportFilter;
import com.procurement.report.dto.response.*;
import com.procurement.report.service.ReportService;
import org.springframework.data.domain.*;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;

@RestController
@RequestMapping("/api/reports")
public class ReportController {
    private final ReportService service;
    public ReportController(ReportService service){this.service=service;}

    @GetMapping("/dashboard")
    public ApiResponse<DashboardResponse> dashboard(){return ApiResponse.success(service.dashboard());}

    @GetMapping("/purchase-requests")
    public ApiResponse<PageResponse<ReportRowResponse>> purchaseRequests(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="requestDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.purchaseRequests(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/approvals")
    public ApiResponse<PageResponse<ReportRowResponse>> approvals(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="assignedDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.approvals(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/rfqs")
    public ApiResponse<PageResponse<ReportRowResponse>> rfqs(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="issueDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.rfqs(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/quotations")
    public ApiResponse<PageResponse<ReportRowResponse>> quotations(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="submissionDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.quotations(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/comparisons")
    public ApiResponse<PageResponse<ReportRowResponse>> comparisons(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="comparisonDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.comparisons(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/purchase-orders")
    public ApiResponse<PageResponse<ReportRowResponse>> purchaseOrders(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="orderDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.purchaseOrders(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/grns")
    public ApiResponse<PageResponse<ReportRowResponse>> grns(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="receiptDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.grns(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/inventory")
    public ApiResponse<PageResponse<ReportRowResponse>> inventory(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="lastStockUpdate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.inventory(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/invoices")
    public ApiResponse<PageResponse<ReportRowResponse>> invoices(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="invoiceDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.invoices(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/three-way-matches")
    public ApiResponse<PageResponse<ReportRowResponse>> threeWayMatches(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="matchDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.threeWayMatches(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/payments")
    public ApiResponse<PageResponse<ReportRowResponse>> payments(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="paymentDate")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.payments(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/vendors")
    public ApiResponse<PageResponse<ReportRowResponse>> vendors(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="title")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.vendors(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/departments")
    public ApiResponse<PageResponse<ReportRowResponse>> departments(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="title")String sort,@RequestParam(defaultValue="desc")String direction){return page(service.departments(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), pageable(page,size,sort,direction)));}
    @GetMapping("/audit-summary")
    public ApiResponse<PageResponse<ReportRowResponse>> auditSummary(@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return page(service.auditSummary(filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId), PageRequest.of(page,size)));}

    @GetMapping("/export/pdf")
    public ApiResponse<ReportExportResponse> exportPdf(@RequestParam String reportType,@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId){return ApiResponse.success(service.exportPdf(reportType, filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId)));}
    @GetMapping("/export/excel")
    public ApiResponse<ReportExportResponse> exportExcel(@RequestParam String reportType,@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId){return ApiResponse.success(service.exportExcel(reportType, filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId)));}
    @GetMapping("/export/csv")
    public ApiResponse<ReportExportResponse> exportCsv(@RequestParam String reportType,@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)Long vendorId,@RequestParam(required=false)Long warehouseId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long productId,@RequestParam(required=false)String status,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long costCenterId){return ApiResponse.success(service.exportCsv(reportType, filter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId)));}

    private ReportFilter filter(LocalDate startDate,LocalDate endDate,Long departmentId,Long vendorId,Long warehouseId,Long categoryId,Long productId,String status,Long employeeId,Long costCenterId){return new ReportFilter(startDate,endDate,departmentId,vendorId,warehouseId,categoryId,productId,status,employeeId,costCenterId);}
    private Pageable pageable(int page,int size,String sort,String direction){return PageRequest.of(page,size,"asc".equalsIgnoreCase(direction)?Sort.by(sort).ascending():Sort.by(sort).descending());}
    private ApiResponse<PageResponse<ReportRowResponse>> page(PageResponse<ReportRowResponse> page){return ApiResponse.success(page);}
}
