import React, { useCallback, useEffect, useState } from "react";
import { DollarSign, RefreshCw, Search, XCircle } from "lucide-react";
import { getAuditLogs } from "../../../../../services/auditService";
import { getReport } from "../../../../../services/reportService";
import { asList } from "../../../../../services/serviceUtils";

export default function FinancialAudits() {
  const [logs, setLogs] = useState([]); const [summary, setSummary] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [keyword, setKeyword] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [auditLogs, auditSummary] = await Promise.all([getAuditLogs({ page: 0, size: 100 }), getReport("audit-summary", { page: 0, size: 100 })]); setLogs(asList(auditLogs)); setSummary(asList(auditSummary)); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const includes = (row) => JSON.stringify(row).toLowerCase().includes(keyword.toLowerCase());
  const visibleSummary = summary.filter(includes); const visibleLogs = logs.filter(includes);
  return <div style={{ padding: 20 }}><div className="aud-page-header" style={{ marginBottom: 24 }}><h1 className="aud-page-title" style={{ display: "flex", alignItems: "center", gap: 10 }}><DollarSign color="#f8b400" /> Financial Audit Activity</h1><p className="aud-page-subtitle">Read-only audit logs and financial audit-summary data from the backend.</p></div><div className="aud-card" style={{ padding: 16, display: "flex", gap: 12, marginBottom: 18 }}><label style={{ display: "flex", gap: 6, alignItems: "center" }}><Search size={15} /><input className="aud-form-input" value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Filter loaded audit records" /></label><button className="aud-btn-primary-sm" onClick={load}><RefreshCw size={14} /> Refresh</button></div>{error && <div className="aud-card" style={{ padding: 14, color: "#b91c1c", marginBottom: 16 }}><XCircle size={16} /> {error} <button onClick={load}>Retry</button></div>}<section className="aud-card" style={{ overflow: "hidden", marginBottom: 18 }}><h2 style={{ padding: "16px 18px", margin: 0, fontSize: 16 }}>Audit summary</h2><div className="aud-table-container"><table className="aud-table"><thead><tr><th>Reference</th><th>Title</th><th>Status</th><th>Amount</th><th>Date</th></tr></thead><tbody>{loading ? <tr><td colSpan="5" style={{ textAlign: "center", padding: 28 }}>Loading audit summary…</td></tr> : visibleSummary.length === 0 ? <tr><td colSpan="5" style={{ textAlign: "center", padding: 28 }}>No financial audit summary records found.</td></tr> : visibleSummary.map((row, index) => <tr key={row.id || index}><td>{row.referenceNumber || row.reference || "—"}</td><td>{row.title || row.description || "—"}</td><td>{row.status || "—"}</td><td>{row.amount ?? "—"}</td><td>{row.date || row.createdAt || "—"}</td></tr>)}</tbody></table></div></section><section className="aud-card" style={{ overflow: "hidden" }}><h2 style={{ padding: "16px 18px", margin: 0, fontSize: 16 }}>Financial audit trail</h2><div className="aud-table-container"><table className="aud-table"><thead><tr><th>Time</th><th>Module</th><th>Operation</th><th>Reference</th><th>Outcome</th></tr></thead><tbody>{loading ? <tr><td colSpan="5" style={{ textAlign: "center", padding: 28 }}>Loading audit logs…</td></tr> : visibleLogs.length === 0 ? <tr><td colSpan="5" style={{ textAlign: "center", padding: 28 }}>No audit logs found.</td></tr> : visibleLogs.map((log) => <tr key={log.id}><td>{log.performedAt || "—"}</td><td>{log.moduleName || "—"}</td><td>{log.operation || "—"}</td><td>{log.referenceNumber || "—"}</td><td>{log.success === false ? "Failed" : "Recorded"}</td></tr>)}</tbody></table></div></section></div>;
}
