import React, { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Boxes, RefreshCw, Search, XCircle } from "lucide-react";
import { getInventory, getLowStockInventory } from "../../../../../services/inventoryService";
import { asList } from "../../../../../services/serviceUtils";

export default function StockManagement() {
  const [items, setItems] = useState([]); const [lowStock, setLowStock] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [keyword, setKeyword] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [inventory, low] = await Promise.all([getInventory({ keyword: keyword || undefined, size: 100 }), getLowStockInventory()]); setItems(asList(inventory)); setLowStock(asList(low)); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [keyword]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  return <div style={{ padding: 20 }}><div className="inv-page-header" style={{ marginBottom: 24 }}><h1 className="inv-page-title" style={{ display: "flex", alignItems: "center", gap: 10 }}><Boxes color="#f8b400" /> Stock Management</h1><p className="inv-page-subtitle">Current inventory quantities from the backend.</p></div>{error && <div className="inv-card" style={{ padding: 14, color: "#b91c1c", marginBottom: 16 }}><XCircle size={16} /> {error} <button onClick={load}>Retry</button></div>}<div className="inv-card" style={{ padding: 16, display: "flex", gap: 12, flexWrap: "wrap", marginBottom: 20 }}><label style={{ display: "flex", alignItems: "center", gap: 6 }}><Search size={15} /><input className="inv-form-input" value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Search product or SKU" /></label><button className="inv-sidebar-toggle" onClick={load}><RefreshCw size={14} /> Refresh</button></div><div className="inv-card" style={{ padding: 16, marginBottom: 20, color: "#9a6700", background: "#fff9e8" }}><AlertTriangle size={16} /> Inventory movement and transfer history are unavailable because the backend does not provide a movement API. Quantities below are live records only.</div><div className="inv-card" style={{ overflow: "hidden" }}><div className="inv-table-container"><table className="inv-table"><thead><tr><th>SKU</th><th>Product</th><th>Warehouse</th><th>Available</th><th>Reserved</th><th>Damaged</th><th>Reorder level</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td colSpan="8" style={{ padding: 32, textAlign: "center" }}>Loading inventory…</td></tr> : items.length === 0 ? <tr><td colSpan="8" style={{ padding: 32, textAlign: "center" }}>No inventory records found.</td></tr> : items.map((item) => <tr key={item.id}><td>{item.productCode}</td><td>{item.productName}</td><td>{item.warehouseName || item.warehouseCode}</td><td>{item.availableQuantity}</td><td>{item.reservedQuantity}</td><td>{item.damagedQuantity}</td><td>{item.reorderLevel}</td><td>{item.status}{lowStock.some((low) => low.id === item.id) ? " · Low stock" : ""}</td></tr>)}</tbody></table></div></div></div>;
}
