package com.procurement.invoice.service;

import com.procurement.common.exception.*;
import com.procurement.common.response.*;
import com.procurement.event.BusinessEventPublisher;
import com.procurement.event.BusinessEventType;
import com.procurement.goodsreceipt.repository.*;
import com.procurement.invoice.dto.request.*;
import com.procurement.invoice.dto.response.*;
import com.procurement.invoice.entity.*;
import com.procurement.invoice.exception.*;
import com.procurement.invoice.mapper.*;
import com.procurement.invoice.repository.*;
import com.procurement.notification.entity.NotificationType;
import com.procurement.purchaseorder.repository.*;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.Year;
import java.util.List;

@Service
public class InvoiceServiceImpl implements InvoiceService{
    private final InvoiceRepository repo;private final InvoiceLineRepository lineRepo;private final InvoiceAttachmentRepository attachmentRepo;private final InvoiceHistoryRepository historyRepo;private final PurchaseOrderRepository orders;private final PurchaseOrderLineRepository orderLines;private final GoodsReceiptNoteRepository grns;private final GoodsReceiptLineRepository grnLines;private final InvoiceMapper mapper;private final BusinessEventPublisher eventPublisher;
    public InvoiceServiceImpl(InvoiceRepository r,InvoiceLineRepository l,InvoiceAttachmentRepository a,InvoiceHistoryRepository h,PurchaseOrderRepository o,PurchaseOrderLineRepository ol,GoodsReceiptNoteRepository g,GoodsReceiptLineRepository gl,InvoiceMapper m,BusinessEventPublisher eventPublisher){repo=r;lineRepo=l;attachmentRepo=a;historyRepo=h;orders=o;orderLines=ol;grns=g;grnLines=gl;mapper=m;this.eventPublisher=eventPublisher;}
    private String user(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?"system":a.getName();}
    private Invoice find(Long id){return repo.findById(id).orElseThrow(()->new InvoiceNotFoundException(id));}
    private BigDecimal nz(BigDecimal v){return v==null?BigDecimal.ZERO:v;}
    private BigDecimal pct(BigDecimal amount,BigDecimal percentage){return amount.multiply(nz(percentage)).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP);}
    private BigDecimal calc(BigDecimal qty,BigDecimal price,BigDecimal discountPct,BigDecimal taxPct){var base=qty.multiply(price);var discount=pct(base,discountPct);var taxable=base.subtract(discount);var tax=pct(taxable,taxPct);return taxable.add(tax).setScale(2,RoundingMode.HALF_UP);}
    private void record(Invoice invoice,String action,InvoiceStatus oldStatus,InvoiceStatus newStatus,String remarks){historyRepo.save(InvoiceHistory.builder().invoice(invoice).action(action).oldStatus(oldStatus).newStatus(newStatus).remarks(remarks).build());}
    private void recalc(Invoice invoice){List<InvoiceLine> lines=lineRepo.findByInvoiceId(invoice.getId());var subtotal=lines.stream().map(InvoiceLine::getLineAmount).reduce(BigDecimal.ZERO,BigDecimal::add);invoice.setSubtotal(subtotal);invoice.setGrandTotal(subtotal.subtract(nz(invoice.getDiscountAmount())).add(nz(invoice.getTaxAmount())).add(nz(invoice.getShippingCharges())).add(nz(invoice.getOtherCharges())).setScale(2,RoundingMode.HALF_UP));repo.save(invoice);}
    @Transactional public InvoiceResponse create(InvoiceRequest r){var po=orders.findById(r.purchaseOrderId()).orElseThrow(()->new ResourceNotFoundException("Purchase order not found"));var grn=grns.findById(r.goodsReceiptNoteId()).orElseThrow(()->new ResourceNotFoundException("GRN not found"));if(!po.getVendor().getId().equals(grn.getVendor().getId()))throw new BadRequestException("Purchase order and GRN vendors do not match");if(!po.getId().equals(grn.getPurchaseOrder().getId()))throw new BadRequestException("GRN must belong to the purchase order");if(repo.existsByVendorInvoiceNumber(r.vendorInvoiceNumber()))throw new ConflictException("Vendor invoice number already exists");var e=Invoice.builder().invoiceNumber("INV-"+Year.now().getValue()+"-"+String.format("%06d",repo.count()+1)).vendorInvoiceNumber(r.vendorInvoiceNumber()).purchaseOrder(po).goodsReceiptNote(grn).vendor(po.getVendor()).invoiceDate(r.invoiceDate()).receivedDate(LocalDate.now()).dueDate(r.dueDate()).currency(r.currency()).discountAmount(nz(r.discountAmount())).taxAmount(nz(r.taxAmount())).shippingCharges(nz(r.shippingCharges())).otherCharges(nz(r.otherCharges())).paymentTerms(r.paymentTerms()).paymentMethod(r.paymentMethod()).remarks(r.remarks()).createdBy(user()).updatedBy(user()).status(InvoiceStatus.RECEIVED).build();e.setSubtotal(BigDecimal.ZERO);e.setGrandTotal(e.getDiscountAmount().add(e.getTaxAmount()).add(e.getShippingCharges()).add(e.getOtherCharges()));var saved=repo.save(e);record(saved,"CREATED",null,InvoiceStatus.RECEIVED,"Invoice received");eventPublisher.publish(BusinessEventType.INVOICE_CREATED,"Invoice","Invoice",saved.getId(),saved.getInvoiceNumber(),"Invoice received",user(),NotificationType.INVOICE);return mapper.toResponse(saved);}
    @Transactional(readOnly=true) public PageResponse<InvoiceResponse> search(String keyword,Long purchaseOrderId,Long goodsReceiptNoteId,InvoiceStatus status,Pageable pageable){Specification<Invoice> spec=(root,q,b)->{var z=b.conjunction();if(keyword!=null&&!keyword.isBlank()){var k="%"+keyword.toLowerCase()+"%";z=b.and(z,b.or(b.like(b.lower(root.get("invoiceNumber")),k),b.like(b.lower(root.get("vendorInvoiceNumber")),k),b.like(b.lower(root.get("vendor").get("vendorName")),k)));}if(purchaseOrderId!=null)z=b.and(z,b.equal(root.get("purchaseOrder").get("id"),purchaseOrderId));if(goodsReceiptNoteId!=null)z=b.and(z,b.equal(root.get("goodsReceiptNote").get("id"),goodsReceiptNoteId));if(status!=null)z=b.and(z,b.equal(root.get("status"),status));return z;};var page=repo.findAll(spec,pageable).map(mapper::toResponse);return new PageResponse<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages(),page.isLast());}
    @Transactional(readOnly=true) public InvoiceResponse get(Long id){return mapper.toResponse(find(id));}
    @Transactional public InvoiceLineResponse addLine(Long id,InvoiceLineRequest r){var invoice=find(id);if(invoice.getStatus()==InvoiceStatus.APPROVED||invoice.getStatus()==InvoiceStatus.PAID||invoice.getStatus()==InvoiceStatus.CANCELLED)throw new ConflictException("Invoice cannot be changed");var pol=orderLines.findById(r.purchaseOrderLineId()).orElseThrow(()->new ResourceNotFoundException("Purchase order line not found"));var grl=grnLines.findById(r.goodsReceiptLineId()).orElseThrow(()->new ResourceNotFoundException("GRN line not found"));if(!pol.getPurchaseOrder().getId().equals(invoice.getPurchaseOrder().getId()))throw new BadRequestException("Purchase order line does not belong to invoice order");if(!grl.getGoodsReceiptNote().getId().equals(invoice.getGoodsReceiptNote().getId()))throw new BadRequestException("GRN line does not belong to invoice GRN");if(!pol.getProduct().getId().equals(r.productId())||!grl.getProduct().getId().equals(r.productId()))throw new BadRequestException("Invoice product must match PO and GRN product");if(r.quantity().compareTo(BigDecimal.ZERO)<=0)throw new BadRequestException("Quantity must be positive");if(r.quantity().compareTo(pol.getQuantityOrdered().subtract(pol.getQuantityReceived()))>0)throw new BadRequestException("Invoice quantity exceeds ordered quantity");if(r.quantity().compareTo(grl.getAcceptedQuantity())>0)throw new BadRequestException("Invoice quantity exceeds accepted GRN quantity");var line=InvoiceLine.builder().invoice(invoice).purchaseOrderLine(pol).goodsReceiptLine(grl).product(pol.getProduct()).quantity(r.quantity()).unitPrice(r.unitPrice()).discountPercentage(nz(r.discountPercentage())).taxPercentage(nz(r.taxPercentage())).lineAmount(calc(r.quantity(),r.unitPrice(),r.discountPercentage(),r.taxPercentage())).remarks(r.remarks()).build();var saved=lineRepo.save(line);recalc(invoice);record(invoice,"LINE_ADDED",invoice.getStatus(),invoice.getStatus(),"Invoice line added");return mapper.toLineResponse(saved);}
    @Transactional public InvoiceResponse match(Long id){var invoice=find(id);if(lineRepo.findByInvoiceId(id).isEmpty())throw new ConflictException("Invoice must contain lines");var old=invoice.getStatus();invoice.setStatus(InvoiceStatus.MATCHED);invoice.setUpdatedBy(user());var saved=repo.save(invoice);record(saved,"MATCHED",old,InvoiceStatus.MATCHED,"Three-way match completed");return mapper.toResponse(saved);}
    @Transactional public InvoiceResponse approve(Long id){var invoice=find(id);if(invoice.getStatus()!=InvoiceStatus.MATCHED&&invoice.getStatus()!=InvoiceStatus.UNDER_VERIFICATION&&invoice.getStatus()!=InvoiceStatus.MATCH_PENDING)throw new ConflictException("Invoice must be matched before approval");var old=invoice.getStatus();invoice.setStatus(InvoiceStatus.APPROVED);invoice.setUpdatedBy(user());var saved=repo.save(invoice);record(saved,"APPROVED",old,InvoiceStatus.APPROVED,"Invoice approved");eventPublisher.publish(BusinessEventType.INVOICE_APPROVED,"Invoice","Invoice",saved.getId(),saved.getInvoiceNumber(),"Invoice approved",user(),NotificationType.INVOICE);return mapper.toResponse(saved);}
    @Transactional(readOnly=true) public PageResponse<InvoiceLineResponse> lines(Long id,Pageable pageable){var mapped=lineRepo.findByInvoiceId(id).stream().map(mapper::toLineResponse).toList();var page=new PageImpl<>(mapped,pageable,mapped.size());return new PageResponse<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages(),page.isLast());}
    @Transactional public InvoiceAttachmentResponse addAttachment(Long id,String fileName,String filePath,String fileType){var invoice=find(id);var attachment=attachmentRepo.save(InvoiceAttachment.builder().invoice(invoice).fileName(fileName).filePath(filePath).fileType(fileType).build());record(invoice,"ATTACHMENT_ADDED",invoice.getStatus(),invoice.getStatus(),fileName);return mapper.toAttachmentResponse(attachment);}
    @Transactional(readOnly=true) public PageResponse<InvoiceAttachmentResponse> attachments(Long id,Pageable pageable){var mapped=attachmentRepo.findByInvoiceId(id).stream().map(mapper::toAttachmentResponse).toList();var page=new PageImpl<>(mapped,pageable,mapped.size());return new PageResponse<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages(),page.isLast());}
    @Transactional(readOnly=true) public PageResponse<InvoiceHistoryResponse> history(Long id,Pageable pageable){var mapped=historyRepo.findByInvoiceIdOrderByPerformedAtDesc(id).stream().map(mapper::toHistoryResponse).toList();var page=new PageImpl<>(mapped,pageable,mapped.size());return new PageResponse<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages(),page.isLast());}
}
