import React, { useState, useEffect, useCallback } from "react";
import {
  Bell,
  CheckCircle2,
  FileText,
  ShieldAlert,
  CheckCheck,
  Package,
  AlertTriangle,
  Loader2,
} from "lucide-react";
import { apiGet, apiPost } from "../../../../../services/apiClient";
import { formatDateIN } from "../../../../../utils/format";

const TYPE_META = {
  APPROVAL: { label: "Approval", color: "#d97706", icon: CheckCircle2 },
  PURCHASE_REQUEST: { label: "Request", color: "#2563eb", icon: FileText },
  PURCHASE_ORDER: { label: "Purchase Order", color: "#0d9488", icon: Package },
  SYSTEM: { label: "System", color: "#64748b", icon: ShieldAlert },
  SECURITY: { label: "Security", color: "#dc2626", icon: ShieldAlert },
  BUDGET: { label: "Budget", color: "#7c3aed", icon: AlertTriangle },
  INVENTORY: { label: "Inventory", color: "#0891b2", icon: Package },
};

const NotificationsModule = ({ onNotifyRefresh }) => {
  const [notifications, setNotifications] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [page, setPage] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [totalElements, setTotalElements] = useState(0);
  const pageSize = 15;

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const data = await apiGet(`/api/notifications/my?page=${page}&size=${pageSize}`);
      setNotifications(data.content || []);
      setTotalPages(data.totalPages || 0);
      setTotalElements(data.totalElements || 0);
      if (onNotifyRefresh) onNotifyRefresh();
    } catch (err) {
      setError(err.message || "Unable to load notifications.");
    } finally {
      setLoading(false);
    }
  }, [page, onNotifyRefresh]);

  useEffect(() => {
    load();
  }, [load]);

  const markRead = async (id) => {
    try {
      await apiPost(`/api/notifications/${id}/mark-read`);
      setNotifications((prev) => prev.map((n) => (n.notificationId === id ? { ...n, read: true } : n)));
      if (onNotifyRefresh) onNotifyRefresh();
    } catch {
      /* ignore */
    }
  };

  const markAllRead = async () => {
    for (const n of notifications.filter((n) => !n.read)) {
      await apiPost(`/api/notifications/${n.notificationId}/mark-read`).catch(() => null);
    }
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
    if (onNotifyRefresh) onNotifyRefresh();
  };

  return (
    <div style={{ padding: "20px", maxWidth: 900, margin: "0 auto" }}>
      <div className="emp-page-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 12, marginBottom: 18 }}>
        <div>
          <h1 className="emp-page-title" style={{ display: "flex", alignItems: "center", gap: 10, margin: 0, fontSize: 22 }}>
            <Bell color="#2563eb" /> Notifications
          </h1>
          <p className="emp-page-subtitle" style={{ margin: "4px 0 0", color: "#666", fontSize: 13 }}>
            Events generated by the backend workflow — {totalElements} total, {notifications.filter((n) => !n.read).length} unread on this page.
          </p>
        </div>
        <button className="emp-btn-primary-sm" style={{ display: "inline-flex", alignItems: "center", gap: 7 }} onClick={markAllRead}>
          <CheckCheck size={15} /> Mark All Read
        </button>
      </div>

      {error && (
        <div style={{ background: "#fef2f2", border: "1px solid #fecaca", color: "#991b1b", borderRadius: 10, padding: "12px 14px", marginBottom: 14, fontSize: 13 }}>{error}</div>
      )}

      <div style={{ background: "#fff", border: "1px solid #e7ebf0", borderRadius: 14, overflow: "hidden" }}>
        {loading ? (
          <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 12, padding: "70px 0", color: "#888", fontWeight: 600 }}>
            <Loader2 size={22} className="lro-spin" /> Loading notifications…
          </div>
        ) : notifications.length === 0 ? (
          <div style={{ padding: "60px 20px", textAlign: "center", color: "#9aa8b8" }}>
            <Bell size={28} style={{ marginBottom: 10, opacity: 0.6 }} />
            <div style={{ fontWeight: 700, fontSize: 15, color: "#475569" }}>No notifications yet</div>
            <div style={{ fontSize: 13, marginTop: 4 }}>You will be notified when your requests are submitted, approved, returned or routed.</div>
          </div>
        ) : (
          notifications.map((n) => {
            const meta = TYPE_META[n.type] || TYPE_META.SYSTEM;
            const Icon = meta.icon;
            return (
              <div
                key={n.id}
                style={{
                  display: "flex",
                  gap: 14,
                  padding: "15px 18px",
                  borderBottom: "1px solid #f2f4f6",
                  background: n.read ? "#fff" : "#f0f7ff",
                }}
              >
                <div style={{ width: 40, height: 40, borderRadius: 10, background: `${meta.color}14`, color: meta.color, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                  <Icon size={18} />
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 }}>
                    <strong style={{ fontSize: 13.5, color: "#111" }}>{n.title}</strong>
                    <span style={{ fontSize: 11.5, color: "#94a3b8", whiteSpace: "nowrap" }}>{formatDateIN(n.createdAt)}</span>
                  </div>
                  <p style={{ margin: "4px 0 6px", fontSize: 13, color: "#475569", lineHeight: 1.45 }}>{n.message}</p>
                  <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                    <span style={{ fontSize: 11, fontWeight: 800, color: meta.color, background: `${meta.color}12`, padding: "2px 8px", borderRadius: 999 }}>{meta.label}</span>
                    {!n.read && (
                      <button
                        onClick={() => markRead(n.notificationId)}
                        style={{ border: "none", background: "none", color: "#2563eb", fontWeight: 700, fontSize: 12, cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 4 }}
                      >
                        <CheckCheck size={13} /> Mark as read
                      </button>
                    )}
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>

      {!loading && totalPages > 1 && (
        <div style={{ display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 10, marginTop: 14, fontSize: 13 }}>
          <button disabled={page === 0} style={{ border: "1px solid #d7dce3", background: page === 0 ? "#f1f5f9" : "#fff", color: page === 0 ? "#b6c2cf" : "#334155", padding: "7px 14px", borderRadius: 8, fontWeight: 700, cursor: page === 0 ? "not-allowed" : "pointer" }} onClick={() => setPage(page - 1)}>Prev</button>
          <span style={{ color: "#475569", fontWeight: 600 }}>Page {page + 1} of {Math.max(totalPages, 1)}</span>
          <button disabled={page >= totalPages - 1} style={{ border: "1px solid #d7dce3", background: page >= totalPages - 1 ? "#f1f5f9" : "#fff", color: page >= totalPages - 1 ? "#b6c2cf" : "#334155", padding: "7px 14px", borderRadius: 8, fontWeight: 700, cursor: page >= totalPages - 1 ? "not-allowed" : "pointer" }} onClick={() => setPage(page + 1)}>Next</button>
        </div>
      )}
    </div>
  );
};

export default NotificationsModule;
