package com.procurement.payment.service;

import com.procurement.common.exception.*;
import com.procurement.common.response.*;
import com.procurement.event.BusinessEventPublisher;
import com.procurement.event.BusinessEventType;
import com.procurement.invoice.entity.*;
import com.procurement.invoice.repository.*;
import com.procurement.notification.entity.NotificationType;
import com.procurement.payment.dto.request.*;
import com.procurement.payment.dto.response.*;
import com.procurement.payment.entity.*;
import com.procurement.payment.exception.PaymentNotFoundException;
import com.procurement.payment.mapper.PaymentMapper;
import com.procurement.payment.repository.*;
import com.procurement.payment.specification.PaymentSpecification;
import com.procurement.threewaymatch.entity.ThreeWayMatchStatus;
import com.procurement.threewaymatch.repository.ThreeWayMatchRepository;
import com.procurement.vendor.entity.Vendor;
import com.procurement.vendor.repository.VendorRepository;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.Year;
import java.util.List;

@Service
public class PaymentServiceImpl implements PaymentService {
    private final PaymentRepository repo; private final PaymentAllocationRepository allocationRepo; private final PaymentAttachmentRepository attachmentRepo; private final PaymentHistoryRepository historyRepo; private final InvoiceRepository invoiceRepo; private final InvoiceLineRepository invoiceLineRepo; private final ThreeWayMatchRepository matchRepo; private final VendorRepository vendorRepo; private final PaymentMapper mapper; private final BusinessEventPublisher eventPublisher;
    public PaymentServiceImpl(PaymentRepository repo, PaymentAllocationRepository allocationRepo, PaymentAttachmentRepository attachmentRepo, PaymentHistoryRepository historyRepo, InvoiceRepository invoiceRepo, InvoiceLineRepository invoiceLineRepo, ThreeWayMatchRepository matchRepo, VendorRepository vendorRepo, PaymentMapper mapper, BusinessEventPublisher eventPublisher){this.repo=repo;this.allocationRepo=allocationRepo;this.attachmentRepo=attachmentRepo;this.historyRepo=historyRepo;this.invoiceRepo=invoiceRepo;this.invoiceLineRepo=invoiceLineRepo;this.matchRepo=matchRepo;this.vendorRepo=vendorRepo;this.mapper=mapper;this.eventPublisher=eventPublisher;}
    private String user(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?"system":a.getName();}
    private Payment find(Long id){return repo.findById(id).orElseThrow(()->new PaymentNotFoundException(id));}
    private BigDecimal nz(BigDecimal v){return v==null?BigDecimal.ZERO:v;}
    private void history(Payment p,String action,PaymentStatus oldStatus,PaymentStatus newStatus,String remarks){historyRepo.save(PaymentHistory.builder().payment(p).action(action).performedBy(user()).oldStatus(oldStatus).newStatus(newStatus).remarks(remarks).build());}
    private BigDecimal allocatedForInvoice(Long invoiceId){return allocationRepo.findByInvoiceId(invoiceId).stream().map(PaymentAllocation::getAllocatedAmount).reduce(BigDecimal.ZERO,BigDecimal::add);}
    private BigDecimal invoiceTotal(Invoice invoice){return invoice.getGrandTotal();}
    private void recalc(Payment payment){var allocations=allocationRepo.findByPaymentId(payment.getId());var paid=allocations.stream().map(PaymentAllocation::getAllocatedAmount).reduce(BigDecimal.ZERO,BigDecimal::add);payment.setPaidAmount(paid);payment.setBalanceAmount(payment.getNetAmount().subtract(paid).max(BigDecimal.ZERO));if(paid.compareTo(BigDecimal.ZERO)==0)payment.setStatus(payment.getStatus()==PaymentStatus.APPROVED?PaymentStatus.APPROVED:PaymentStatus.DRAFT);else if(payment.getBalanceAmount().compareTo(BigDecimal.ZERO)>0)payment.setStatus(PaymentStatus.PARTIALLY_PAID);else payment.setStatus(PaymentStatus.PAID);repo.save(payment);}
    @Transactional public PaymentResponse create(PaymentRequest r){var invoice=invoiceRepo.findById(r.invoiceId()).orElseThrow(()->new ResourceNotFoundException("Invoice not found"));var match=matchRepo.findById(r.threeWayMatchId()).orElseThrow(()->new ResourceNotFoundException("Three-way match not found"));if(invoice.getStatus()!=InvoiceStatus.MATCHED&&invoice.getStatus()!=InvoiceStatus.APPROVED)throw new ConflictException("Invoice must be MATCHED or APPROVED");if(match.getStatus()!=ThreeWayMatchStatus.APPROVED)throw new ConflictException("Three-way match must be APPROVED");if(!invoice.getId().equals(match.getInvoice().getId()))throw new BadRequestException("Invoice does not belong to three-way match");if(!invoice.getPurchaseOrder().getId().equals(r.purchaseOrderId()))throw new BadRequestException("Purchase order mismatch");if(!invoice.getVendor().getStatus().equalsIgnoreCase("ACTIVE"))throw new ConflictException("Vendor must be active");if(repo.existsByPaymentNumber("PAY-"+Year.now().getValue()+"-"+String.format("%06d",repo.count()+1)))throw new ConflictException("Payment number already exists");var net=nz(r.grossAmount()).subtract(nz(r.discountAmount())).subtract(nz(r.taxDeduction())).subtract(nz(r.otherDeduction()));var p=Payment.builder().paymentNumber("PAY-"+Year.now().getValue()+"-"+String.format("%06d",repo.count()+1)).vendor(invoice.getVendor()).invoice(invoice).threeWayMatch(match).purchaseOrder(invoice.getPurchaseOrder()).paymentDate(r.paymentDate()).scheduledDate(r.scheduledDate()).paymentMethod(r.paymentMethod()).paymentReference(r.paymentReference()).bankReference(r.bankReference()).currency(r.currency()==null?invoice.getCurrency():r.currency()).grossAmount(nz(r.grossAmount())).discountAmount(nz(r.discountAmount())).taxDeduction(nz(r.taxDeduction())).otherDeduction(nz(r.otherDeduction())).netAmount(net).paidAmount(BigDecimal.ZERO).balanceAmount(net).remarks(r.remarks()).createdBy(user()).updatedBy(user()).status(r.scheduledDate()!=null&&r.scheduledDate().isAfter(LocalDate.now())?PaymentStatus.SCHEDULED:PaymentStatus.DRAFT).build();var saved=repo.save(p);history(saved,"CREATED",null,saved.getStatus(),"Payment created");return mapper.toResponse(saved);}
    @Transactional(readOnly=true) public PageResponse<PaymentResponse> search(String keyword, Long vendorId, PaymentStatus status, String paymentMethod, Pageable pageable){var page=repo.findAll(PaymentSpecification.search(keyword,vendorId,status,paymentMethod),pageable).map(mapper::toResponse);return new PageResponse<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages(),page.isLast());}
    @Transactional(readOnly=true) public PaymentResponse get(Long id){return mapper.toResponse(find(id));}
    @Transactional public PaymentResponse update(Long id, PaymentRequest r){var p=find(id);if(p.getStatus()==PaymentStatus.APPROVED||p.getStatus()==PaymentStatus.PROCESSING||p.getStatus()==PaymentStatus.PAID||p.getStatus()==PaymentStatus.CANCELLED)throw new ConflictException("Payment cannot be changed");var old=p.getStatus();p.setPaymentDate(r.paymentDate());p.setScheduledDate(r.scheduledDate());p.setPaymentMethod(r.paymentMethod());p.setPaymentReference(r.paymentReference());p.setBankReference(r.bankReference());p.setCurrency(r.currency()==null?p.getCurrency():r.currency());p.setGrossAmount(nz(r.grossAmount()));p.setDiscountAmount(nz(r.discountAmount()));p.setTaxDeduction(nz(r.taxDeduction()));p.setOtherDeduction(nz(r.otherDeduction()));p.setNetAmount(p.getGrossAmount().subtract(p.getDiscountAmount()).subtract(p.getTaxDeduction()).subtract(p.getOtherDeduction()));p.setBalanceAmount(p.getNetAmount().subtract(p.getPaidAmount()).max(BigDecimal.ZERO));p.setRemarks(r.remarks());p.setUpdatedBy(user());var saved=repo.save(p);history(saved,"UPDATED",old,saved.getStatus(),"Payment updated");return mapper.toResponse(saved);}
    @Transactional public void delete(Long id){var p=find(id);if(p.getStatus()!=PaymentStatus.DRAFT&&p.getStatus()!=PaymentStatus.CANCELLED)throw new ConflictException("Only draft or cancelled payments can be deleted");repo.delete(p);}
    @Transactional public PaymentResponse approve(Long id){var p=find(id);var old=p.getStatus();p.setStatus(PaymentStatus.APPROVED);p.setUpdatedBy(user());var saved=repo.save(p);history(saved,"APPROVED",old,PaymentStatus.APPROVED,"Payment approved");return mapper.toResponse(saved);}
    @Transactional public PaymentResponse process(Long id){var p=find(id);if(p.getStatus()!=PaymentStatus.APPROVED&&p.getStatus()!=PaymentStatus.SCHEDULED)throw new ConflictException("Payment must be approved or scheduled");var old=p.getStatus();p.setStatus(PaymentStatus.PROCESSING);p.setUpdatedBy(user());var saved=repo.save(p);history(saved,"PROCESSING",old,PaymentStatus.PROCESSING,"Payment processing started");eventPublisher.publish(BusinessEventType.PAYMENT_PROCESSED,"Payment","Payment",saved.getId(),saved.getPaymentNumber(),"Payment processing started",user(),NotificationType.PAYMENT);return mapper.toResponse(saved);}
    @Transactional public PaymentResponse complete(Long id){var p=find(id);var old=p.getStatus();p.setStatus(PaymentStatus.PAID);p.setPaidAmount(p.getNetAmount());p.setBalanceAmount(BigDecimal.ZERO.setScale(2,RoundingMode.HALF_UP));p.setPaymentDate(LocalDate.now());p.setUpdatedBy(user());var saved=repo.save(p);var invoice=p.getInvoice();var invoiceBalance=invoice.getGrandTotal().subtract(allocatedForInvoice(invoice.getId()));invoice.setStatus(invoiceBalance.compareTo(BigDecimal.ZERO)<=0?InvoiceStatus.PAID:InvoiceStatus.PARTIALLY_PAID);invoiceRepo.save(invoice);history(saved,"COMPLETED",old,PaymentStatus.PAID,"Payment completed");eventPublisher.publish(BusinessEventType.PAYMENT_COMPLETED,"Payment","Payment",saved.getId(),saved.getPaymentNumber(),"Payment completed",user(),NotificationType.PAYMENT);return mapper.toResponse(saved);}
    @Transactional public PaymentResponse fail(Long id){var p=find(id);var old=p.getStatus();p.setStatus(PaymentStatus.FAILED);p.setUpdatedBy(user());var saved=repo.save(p);history(saved,"FAILED",old,PaymentStatus.FAILED,"Payment failed");return mapper.toResponse(saved);}
    @Transactional public PaymentResponse cancel(Long id){var p=find(id);var old=p.getStatus();p.setStatus(PaymentStatus.CANCELLED);p.setUpdatedBy(user());var saved=repo.save(p);history(saved,"CANCELLED",old,PaymentStatus.CANCELLED,"Payment cancelled");return mapper.toResponse(saved);}
    @Transactional public PaymentAllocationResponse addAllocation(Long id, PaymentAllocationRequest r){var payment=find(id);var invoice=invoiceRepo.findById(r.invoiceId()).orElseThrow(()->new ResourceNotFoundException("Invoice not found"));if(payment.getInvoice()!=null&& !payment.getInvoice().getId().equals(invoice.getId()))throw new BadRequestException("Allocation invoice mismatch");var invoiceAllocated=allocatedForInvoice(invoice.getId());var invoiceBalance=invoice.getGrandTotal().subtract(invoiceAllocated);if(r.allocatedAmount().compareTo(invoiceBalance)>0)throw new ConflictException("Allocated amount cannot exceed invoice balance");var allocation=PaymentAllocation.builder().payment(payment).invoice(invoice).allocatedAmount(r.allocatedAmount()).remainingAmount(invoiceBalance.subtract(r.allocatedAmount())).remarks(r.remarks()).build();var saved=allocationRepo.save(allocation);payment.setPaidAmount(payment.getPaidAmount().add(r.allocatedAmount()));payment.setBalanceAmount(payment.getNetAmount().subtract(payment.getPaidAmount()).max(BigDecimal.ZERO));payment.setStatus(payment.getBalanceAmount().compareTo(BigDecimal.ZERO)>0?PaymentStatus.PARTIALLY_PAID:PaymentStatus.PAID);payment.setUpdatedBy(user());repo.save(payment);var invBalance=invoice.getGrandTotal().subtract(allocatedForInvoice(invoice.getId()).add(r.allocatedAmount()));invoice.setStatus(invBalance.compareTo(BigDecimal.ZERO)<=0?InvoiceStatus.PAID:InvoiceStatus.PARTIALLY_PAID);invoiceRepo.save(invoice);history(payment,"ALLOCATION_ADDED",payment.getStatus(),payment.getStatus(),"Invoice allocation added");return mapper.toAllocationResponse(saved);}
    @Transactional(readOnly=true) public PageResponse<PaymentAllocationResponse> allocations(Long id, Pageable pageable){var mapped=allocationRepo.findByPaymentId(id).stream().map(mapper::toAllocationResponse).toList();var page=new PageImpl<>(mapped,pageable,mapped.size());return new PageResponse<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages(),page.isLast());}
    @Transactional public PaymentAttachmentResponse addAttachment(Long id,String fileName,String filePath,String fileType){var payment=find(id);var attachment=attachmentRepo.save(PaymentAttachment.builder().payment(payment).fileName(fileName).filePath(filePath).fileType(fileType).build());history(payment,"ATTACHMENT_ADDED",payment.getStatus(),payment.getStatus(),fileName);return mapper.toAttachmentResponse(attachment);}
    @Transactional(readOnly=true) public PageResponse<PaymentAttachmentResponse> attachments(Long id, Pageable pageable){var mapped=attachmentRepo.findByPaymentId(id).stream().map(mapper::toAttachmentResponse).toList();var page=new PageImpl<>(mapped,pageable,mapped.size());return new PageResponse<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages(),page.isLast());}
    @Transactional public void deleteAttachment(Long id, Long attachmentId){var payment=find(id);var attachment=attachmentRepo.findById(attachmentId).orElseThrow(()->new ResourceNotFoundException("Attachment not found"));if(!attachment.getPayment().getId().equals(payment.getId()))throw new BadRequestException("Attachment does not belong to payment");attachmentRepo.delete(attachment);}
    @Transactional(readOnly=true) public PageResponse<PaymentHistoryResponse> history(Long id, Pageable pageable){var mapped=historyRepo.findByPaymentIdOrderByPerformedAtDesc(id).stream().map(mapper::toHistoryResponse).toList();var page=new PageImpl<>(mapped,pageable,mapped.size());return new PageResponse<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages(),page.isLast());}
}
