spring.application.name=backend

spring.profiles.active=dev

server.port=8080

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.security.jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLWRldmVsb3BtZW50LXNlY3JldC1rZXktbXVzdC1iZS1sb25nLWVub3VnaC0yNTYtYml0cw==}
app.security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
