import React, { useEffect, useState } from "react";
import { AlertCircle, CheckCircle2, FileText, PauseCircle, PlayCircle, XCircle } from "lucide-react";
import { cancelRfq, closeRfq, getRfqs, openRfq } from "../../../../../services/rfqService";

const list = (data) => Array.isArray(data) ? data : data?.content || [];
const show = (value) => String(value || "—").replaceAll("_", " ");
const RfqManagement = () => {
  const [rfqs, setRfqs] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setRfqs(list(await getRfqs())); } catch (loadError) { setError(loadError.message || "Unable to load RFQs."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const change = async (id, action) => { setBusy(`${id}-${action}`); setError(""); try { await ({ open: openRfq, close: closeRfq, cancel: cancelRfq })[action](id); await load(); } catch (actionError) { setError(actionError.message || "Unable to update the RFQ."); } finally { setBusy(""); } };
  return <div className="pe-rfq-management-container"><div className="pe-page-header"><div><h1 className="pe-page-title"><FileText color="#f8b400" /> RFQ management</h1><p className="pe-page-subtitle">RFQs and lifecycle actions recorded by the backend.</p></div></div>{error && <div className="pe-card" style={{ padding: 16, color: "#b91c1c", marginBottom: 16 }}><AlertCircle size={16} /> {error} <button className="pe-btn-primary-sm" onClick={load}>Retry</button></div>}<div className="pe-card"><div className="pe-table-container"><table className="pe-table"><thead><tr><th>RFQ</th><th>Purchase request</th><th>Closing date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading && <tr><td colSpan="5" style={{ padding: 28, textAlign: "center" }}>Loading RFQs…</td></tr>}{!loading && rfqs.length === 0 && <tr><td colSpan="5" style={{ padding: 28, textAlign: "center" }}>No RFQs are available.</td></tr>}{rfqs.map((rfq) => <tr key={rfq.id}><td><strong>{rfq.rfqNumber || rfq.id}</strong></td><td>{rfq.purchaseRequestNumber || rfq.purchaseRequestId || "—"}</td><td>{rfq.closingDate || "—"}</td><td><span className="emp-priority medium">{show(rfq.status)}</span></td><td style={{ display: "flex", gap: 8 }}>{rfq.status === "DRAFT" && <button className="pe-btn-primary-sm" disabled={busy === `${rfq.id}-open`} onClick={() => change(rfq.id, "open")}><PlayCircle size={14} /> Open</button>}{rfq.status === "OPEN" && <button className="pe-btn-primary-sm" disabled={busy === `${rfq.id}-close`} onClick={() => change(rfq.id, "close")}><PauseCircle size={14} /> Close</button>}{!["CANCELLED", "CLOSED"].includes(rfq.status) && <button className="pe-btn-primary-sm" disabled={busy === `${rfq.id}-cancel`} onClick={() => change(rfq.id, "cancel")} style={{ background: "#b91c1c", color: "#fff" }}><XCircle size={14} /> Cancel</button>}</td></tr>)}</tbody></table></div></div></div>;
};
export default RfqManagement;
