import React, { useEffect, useState } from "react";
import { AlertCircle, Eye, FileCheck2 } from "lucide-react";
import { getVendorQuotationLines, getVendorQuotations } from "../../../../../services/quotationService";

const list = (data) => Array.isArray(data) ? data : data?.content || [];
const text = (value) => String(value || "—").replaceAll("_", " ");
const money = (value, currency = "INR") => value === null || value === undefined ? "—" : new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(value);
const VendorQuotations = () => {
  const [quotes, setQuotes] = useState([]); const [selected, setSelected] = useState(null); const [lines, setLines] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [detailLoading, setDetailLoading] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { setQuotes(list(await getVendorQuotations())); } catch (loadError) { setError(loadError.message || "Unable to load vendor quotations."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const open = async (quote) => { setSelected(quote); setDetailLoading(true); try { setLines(list(await getVendorQuotationLines({ vendorQuotationId: quote.id }))); } catch (detailError) { setError(detailError.message || "Unable to load quotation lines."); setLines([]); } finally { setDetailLoading(false); } };
  return <div className="pe-quotations-container"><div className="pe-page-header"><div><h1 className="pe-page-title"><FileCheck2 color="#f8b400" /> Vendor quotations</h1><p className="pe-page-subtitle">Submitted backend quotations and their commercial line items.</p></div></div>{error && <div className="pe-card" style={{ padding: 16, color: "#b91c1c", marginBottom: 16 }}><AlertCircle size={16} /> {error} <button className="pe-btn-primary-sm" onClick={load}>Retry</button></div>}<div className="pe-card"><div className="pe-table-container"><table className="pe-table"><thead><tr><th>Quotation</th><th>RFQ</th><th>Vendor</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{loading && <tr><td colSpan="6" style={{ padding: 28, textAlign: "center" }}>Loading quotations…</td></tr>}{!loading && quotes.length === 0 && <tr><td colSpan="6" style={{ padding: 28, textAlign: "center" }}>No vendor quotations have been submitted.</td></tr>}{quotes.map((quote) => <tr key={quote.id}><td>{quote.quotationNumber || quote.id}</td><td>{quote.rfqNumber || quote.rfqId || "—"}</td><td>{quote.vendorName || quote.vendorId || "—"}</td><td>{money(quote.totalAmount ?? quote.grandTotal, quote.currency)}</td><td>{text(quote.status)}</td><td><button className="pe-btn-primary-sm" onClick={() => open(quote)}><Eye size={14} /> Details</button></td></tr>)}</tbody></table></div></div>{selected && <div className="pe-card" style={{ marginTop: 20, padding: 20 }}><h3>{selected.quotationNumber || selected.id} line items</h3>{detailLoading ? <p>Loading line items…</p> : lines.length === 0 ? <p>No quotation lines are recorded.</p> : <table className="pe-table"><thead><tr><th>Product</th><th>Quantity</th><th>Unit price</th><th>Total</th></tr></thead><tbody>{lines.map((line) => <tr key={line.id}><td>{line.productName || line.description || "—"}</td><td>{line.quantity ?? "—"}</td><td>{money(line.unitPrice, selected.currency)}</td><td>{money(line.lineTotal ?? line.totalAmount, selected.currency)}</td></tr>)}</tbody></table>}</div>}</div>;
};
export default VendorQuotations;
