import React, { useEffect, useState } from "react";
import { AlertCircle, Award, FileCheck2 } from "lucide-react";
import { getQuotationComparisons } from "../../../../../services/quotationComparisonService";
import { getVendorQuotationLines, getVendorQuotations } from "../../../../../services/quotationService";

const list = (data) => Array.isArray(data) ? data : data?.content || [];
const label = (value) => String(value || "—").replaceAll("_", " ");
const money = (value, currency = "INR") => value === null || value === undefined ? "—" : new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(value);
const VendorSelection = () => {
  const [comparisons, setComparisons] = useState([]); const [quotes, setQuotes] = useState([]); const [selectedId, setSelectedId] = useState(""); const [lines, setLines] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [comparisonRows, quoteRows] = await Promise.all([getQuotationComparisons(), getVendorQuotations()]); setComparisons(list(comparisonRows)); setQuotes(list(quoteRows)); setSelectedId((id) => id || String(list(comparisonRows)[0]?.id || "")); } catch (loadError) { setError(loadError.message || "Unable to load quotation comparisons."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const selected = comparisons.find((entry) => String(entry.id) === selectedId);
  const comparisonQuotes = quotes.filter((quote) => String(quote.quotationComparisonId || quote.comparisonId || "") === selectedId || String(quote.rfqId || "") === String(selected?.rfqId || ""));
  const loadLines = async (quote) => { try { setLines((current) => ({ ...current, [quote.id]: { loading: true } })); const rows = list(await getVendorQuotationLines({ vendorQuotationId: quote.id })); setLines((current) => ({ ...current, [quote.id]: { rows } })); } catch (lineError) { setError(lineError.message || "Unable to load quotation line items."); setLines((current) => ({ ...current, [quote.id]: { rows: [] } })); } };
  return <div className="pe-vendor-selection-container"><div className="pe-page-header"><div><h1 className="pe-page-title"><Award color="#f8b400" /> Quotation comparison</h1><p className="pe-page-subtitle">Backend-created comparison records; recommendation and approval remain backend decisions.</p></div></div>{error && <div className="pe-card" style={{ padding: 16, color: "#b91c1c", marginBottom: 16 }}><AlertCircle size={16} /> {error} <button className="pe-btn-primary-sm" onClick={load}>Retry</button></div>}<div className="pe-card" style={{ padding: 20, marginBottom: 20 }}><select className="pe-form-select" disabled={loading} value={selectedId} onChange={(event) => setSelectedId(event.target.value)} style={{ width: "100%" }}><option value="">Select a comparison</option>{comparisons.map((comparison) => <option key={comparison.id} value={comparison.id}>{comparison.comparisonNumber || comparison.id} — {label(comparison.status)}</option>)}</select></div>{loading && <div className="pe-card" style={{ padding: 30, textAlign: "center" }}>Loading comparisons…</div>}{!loading && !selected && <div className="pe-card" style={{ padding: 30, textAlign: "center" }}>No backend quotation comparisons are available. A comparison must be created before a purchase order can be created.</div>}{selected && <div className="pe-card" style={{ padding: 20 }}><h3>{selected.comparisonNumber || selected.id}</h3><p>Status: <strong>{label(selected.status)}</strong></p><p>RFQ: {selected.rfqNumber || selected.rfqId || "—"}</p><div className="pe-table-container"><table className="pe-table"><thead><tr><th>Vendor</th><th>Quotation</th><th>Amount</th><th>Status</th><th>Lines</th></tr></thead><tbody>{comparisonQuotes.length === 0 && <tr><td colSpan="5" style={{ padding: 24, textAlign: "center" }}>No quotations are linked to this comparison in the backend response.</td></tr>}{comparisonQuotes.map((quote) => <React.Fragment key={quote.id}><tr><td>{quote.vendorName || quote.vendorId || "—"}</td><td>{quote.quotationNumber || quote.id}</td><td>{money(quote.totalAmount ?? quote.grandTotal, quote.currency)}</td><td>{label(quote.status)}</td><td><button className="pe-btn-primary-sm" onClick={() => loadLines(quote)}>{lines[quote.id]?.loading ? "Loading…" : <><FileCheck2 size={14} /> View lines</>}</button></td></tr>{lines[quote.id]?.rows?.map((line) => <tr key={line.id} style={{ background: "#f8f9fb" }}><td colSpan="2">{line.productName || line.description || "—"}</td><td>{line.quantity ?? "—"} × {money(line.unitPrice, quote.currency)}</td><td colSpan="2">{money(line.lineTotal ?? line.totalAmount, quote.currency)}</td></tr>)}</React.Fragment>)}</tbody></table></div><p style={{ fontSize: 12, color: "#666", marginTop: 16 }}>This screen does not manufacture a recommendation. Use the backend comparison workflow to record recommendation or approval before creating a purchase order.</p></div>}</div>;
};
export default VendorSelection;
