package com.procurement.vendorquotation.service;

import com.procurement.common.exception.*;
import com.procurement.common.response.PageResponse;
import com.procurement.rfq.entity.*;
import com.procurement.rfq.repository.*;
import com.procurement.vendor.repository.VendorRepository;
import com.procurement.vendorquotation.dto.request.*;
import com.procurement.vendorquotation.dto.response.*;
import com.procurement.vendorquotation.entity.*;
import com.procurement.vendorquotation.exception.VendorQuotationNotFoundException;
import com.procurement.vendorquotation.mapper.VendorQuotationMapper;
import com.procurement.vendorquotation.repository.*;
import com.procurement.vendorquotation.specification.VendorQuotationSpecification;
import org.springframework.data.domain.*;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*;

@Service
public class VendorQuotationServiceImpl implements VendorQuotationService {
 private final VendorQuotationRepository repo; private final VendorQuotationLineRepository lines; private final QuotationAttachmentRepository attachments; private final RfqRepository rfqs; private final RfqLineRepository rfqLines; private final RfqVendorRepository invitations; private final VendorRepository vendors; private final VendorQuotationMapper mapper;
 public VendorQuotationServiceImpl(VendorQuotationRepository r,VendorQuotationLineRepository l,QuotationAttachmentRepository a,RfqRepository f,RfqLineRepository fl,RfqVendorRepository i,VendorRepository v,VendorQuotationMapper m){repo=r;lines=l;attachments=a;rfqs=f;rfqLines=fl;invitations=i;vendors=v;mapper=m;}
 private String user(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?"system":a.getName();} private BigDecimal n(BigDecimal x){return x==null?BigDecimal.ZERO:x;} private VendorQuotation find(Long id){return repo.findById(id).orElseThrow(()->new VendorQuotationNotFoundException(id));} private void draft(VendorQuotation q){if(q.getStatus()!=VendorQuotationStatus.DRAFT)throw new ConflictException("Submitted quotations cannot be changed");}
 @Transactional public VendorQuotationResponse create(VendorQuotationRequest r){var f=rfqs.findById(r.rfqId()).orElseThrow(()->new ResourceNotFoundException("RFQ not found: "+r.rfqId()));if(f.getStatus()!=RfqStatus.OPEN)throw new ConflictException("RFQ must be OPEN");var v=vendors.findById(r.vendorId()).orElseThrow(()->new ResourceNotFoundException("Vendor not found: "+r.vendorId()));if(!"ACTIVE".equalsIgnoreCase(v.getStatus()))throw new ConflictException("Vendor must be active");invitations.findByRfqIdAndVendorId(r.rfqId(),r.vendorId()).orElseThrow(()->new ConflictException("Vendor is not invited"));if(repo.existsByRfqIdAndVendorId(r.rfqId(),r.vendorId()))throw new ConflictException("Vendor already has a quotation");var q=VendorQuotation.builder().quotationNumber("VQ-"+Year.now().getValue()+"-"+String.format("%06d",repo.count()+1)).rfq(f).vendor(v).validUntil(r.validUntil()).currency(r.currency().toUpperCase()).discountAmount(n(r.discountAmount())).taxAmount(n(r.taxAmount())).shippingCharges(n(r.shippingCharges())).otherCharges(n(r.otherCharges())).paymentTerms(r.paymentTerms()).deliveryDays(r.deliveryDays()).deliveryLocation(r.deliveryLocation()).warrantyMonths(r.warrantyMonths()).remarks(r.remarks()).createdBy(user()).updatedBy(user()).build();return mapper.toResponse(repo.save(q));}
 @Transactional(readOnly=true)public PageResponse<VendorQuotationResponse>search(String k,Long r,Long v,VendorQuotationStatus s,Pageable p){Page<VendorQuotationResponse>x=repo.findAll(VendorQuotationSpecification.search(k,r,v,s),p).map(mapper::toResponse);return new PageResponse<>(x.getContent(),x.getNumber(),x.getSize(),x.getTotalElements(),x.getTotalPages(),x.isLast());}@Transactional(readOnly=true)public VendorQuotationResponse get(Long id){return mapper.toResponse(find(id));}
 @Transactional public VendorQuotationResponse update(Long id,VendorQuotationRequest r){var q=find(id);draft(q);if(!q.getRfq().getId().equals(r.rfqId())||!q.getVendor().getId().equals(r.vendorId()))throw new BadRequestException("RFQ and vendor cannot be changed");q.setValidUntil(r.validUntil());q.setCurrency(r.currency().toUpperCase());q.setDiscountAmount(n(r.discountAmount()));q.setTaxAmount(n(r.taxAmount()));q.setShippingCharges(n(r.shippingCharges()));q.setOtherCharges(n(r.otherCharges()));q.setPaymentTerms(r.paymentTerms());q.setDeliveryDays(r.deliveryDays());q.setDeliveryLocation(r.deliveryLocation());q.setWarrantyMonths(r.warrantyMonths());q.setRemarks(r.remarks());return mapper.toResponse(repo.save(q));}@Transactional public void delete(Long id){var q=find(id);draft(q);repo.delete(q);}
 private void totals(VendorQuotation q){BigDecimal subtotal=BigDecimal.ZERO,discount=BigDecimal.ZERO,tax=BigDecimal.ZERO;for(var l:lines.findByVendorQuotationId(q.getId())){BigDecimal base=l.getQuantity().multiply(l.getUnitPrice());BigDecimal lineDiscount=base.multiply(n(l.getDiscountPercentage())).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP);BigDecimal taxable=base.subtract(lineDiscount);BigDecimal lineTax=taxable.multiply(n(l.getTaxPercentage())).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP);subtotal=subtotal.add(base);discount=discount.add(lineDiscount);tax=tax.add(lineTax);l.setLineAmount(taxable.add(lineTax));lines.save(l);}q.setSubtotal(subtotal);q.setDiscountAmount(discount);q.setTaxAmount(tax);q.setGrandTotal(subtotal.subtract(discount).add(tax).add(n(q.getShippingCharges())).add(n(q.getOtherCharges())));}
 @Transactional public VendorQuotationResponse submit(Long id){var q=find(id);draft(q);if(q.getRfq().getStatus()!=RfqStatus.OPEN||!LocalDate.now().isBefore(q.getRfq().getClosingDate()))throw new ConflictException("RFQ is closed or past its closing date");if(lines.findByVendorQuotationId(id).isEmpty())throw new ConflictException("Quotation must contain at least one line");totals(q);q.setStatus(VendorQuotationStatus.SUBMITTED);q.setSubmissionDate(LocalDate.now());var inv=invitations.findByRfqIdAndVendorId(q.getRfq().getId(),q.getVendor().getId()).orElseThrow(()->new ConflictException("Vendor invitation not found"));inv.setResponseStatus(RfqVendorStatus.RESPONDED);inv.setResponseDate(LocalDateTime.now());invitations.save(inv);return mapper.toResponse(repo.save(q));}
 @Transactional public VendorQuotationResponse withdraw(Long id){var q=find(id);if(q.getStatus()!=VendorQuotationStatus.SUBMITTED)throw new ConflictException("Only submitted quotations can be withdrawn");q.setStatus(VendorQuotationStatus.WITHDRAWN);return mapper.toResponse(repo.save(q));}
 private VendorQuotationLine line(VendorQuotationLineRequest r){var q=find(r.vendorQuotationId());draft(q);var rl=rfqLines.findById(r.rfqLineId()).orElseThrow(()->new ResourceNotFoundException("RFQ line not found: "+r.rfqLineId()));if(!rl.getRfq().getId().equals(q.getRfq().getId()))throw new BadRequestException("RFQ line does not belong to quotation RFQ");if(lines.findByVendorQuotationIdAndRfqLineId(q.getId(),rl.getId()).isPresent())throw new ConflictException("Quotation line already exists");BigDecimal d=n(r.discountPercentage()),t=n(r.taxPercentage()),base=r.quantity().multiply(r.unitPrice()),disc=base.multiply(d).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP),tax=base.subtract(disc).multiply(t).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP);return lines.save(VendorQuotationLine.builder().vendorQuotation(q).rfqLine(rl).product(rl.getProduct()).quantity(r.quantity()).unitPrice(r.unitPrice()).discountPercentage(d).taxPercentage(t).lineAmount(base.subtract(disc).add(tax)).remarks(r.remarks()).build());}
 @Transactional public VendorQuotationLineResponse addLine(VendorQuotationLineRequest r){return mapper.line(line(r));}@Transactional(readOnly=true)public PageResponse<VendorQuotationLineResponse>lines(Long q,Pageable p){Page<VendorQuotationLineResponse>x=lines.findByVendorQuotationId(q,p).map(mapper::line);return new PageResponse<>(x.getContent(),x.getNumber(),x.getSize(),x.getTotalElements(),x.getTotalPages(),x.isLast());}@Transactional(readOnly=true)public VendorQuotationLineResponse getLine(Long id){return lines.findById(id).map(mapper::line).orElseThrow(()->new ResourceNotFoundException("Quotation line not found: "+id));}
 @Transactional public VendorQuotationLineResponse updateLine(Long id,VendorQuotationLineRequest r){var e=lines.findById(id).orElseThrow(()->new ResourceNotFoundException("Quotation line not found: "+id));draft(e.getVendorQuotation());if(!e.getRfqLine().getId().equals(r.rfqLineId()))throw new BadRequestException("RFQ line cannot be changed");BigDecimal d=n(r.discountPercentage()),t=n(r.taxPercentage()),base=r.quantity().multiply(r.unitPrice()),disc=base.multiply(d).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP),tax=base.subtract(disc).multiply(t).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP);e.setQuantity(r.quantity());e.setUnitPrice(r.unitPrice());e.setDiscountPercentage(d);e.setTaxPercentage(t);e.setLineAmount(base.subtract(disc).add(tax));e.setRemarks(r.remarks());return mapper.line(lines.save(e));}@Transactional public void deleteLine(Long id){var e=lines.findById(id).orElseThrow(()->new ResourceNotFoundException("Quotation line not found: "+id));draft(e.getVendorQuotation());lines.delete(e);}
 @Transactional public QuotationAttachmentResponse addAttachment(QuotationAttachmentRequest r){var q=find(r.vendorQuotationId());draft(q);return mapper.attachment(attachments.save(QuotationAttachment.builder().vendorQuotation(q).fileName(r.fileName()).filePath(r.filePath()).fileType(r.fileType()).build()));}@Transactional(readOnly=true)public PageResponse<QuotationAttachmentResponse>attachments(Long q,Pageable p){Page<QuotationAttachment> x=attachments.findByVendorQuotationId(q,p);var z=x.map(mapper::attachment);return new PageResponse<>(z.getContent(),z.getNumber(),z.getSize(),z.getTotalElements(),z.getTotalPages(),z.isLast());}
}
